# name: Generate terraform docs
# on:
#   - pull_request

# jobs:
#   docs:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#       with:
#         ref: ${{ github.event.pull_request.head.ref }}

#     - name: Render terraform docs and push changes back to PR
#       uses: terraform-docs/gh-actions@main
#       with:
#         working-dir: .
#         output-file: README.md
#         output-method: inject
#         git-push: "true"


name: VPC Terratest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  go-tests:
    name: Run Go VPC Terratest
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.6.1
        with:
          role-to-assume: arn:aws:iam::853333176435:role/github-actions-${{ github.event.repository.name }}
          aws-region: us-east-1
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.13.1
      - name: Setup Terraform
        uses: autero1/action-terraform@v1.0.3
        with:
          terraform_version: 1.0.9
      - name: Download Go Modules
        working-directory: test
        run: go mod download
      - name: Run Go Tests
        working-directory: test
        run: go test -v